[terminal]
vt = 1

[default_session]
command = "Hyprland"
user = $USER

[tuigreet_session]
command = "tuigreet --cmd Hyprland"
user = $USER

[initial_session]
command = "Hyprland --config /etc/greetd/hyprland.conf"
user = "greeter"